spring.application.name=UNote

spring.datasource.url=jdbc:postgresql://localhost:5432/unote_test
spring.datasource.username=postgres
spring.datasource.password=L@KEhouse11
spring.datasource.driver-class-name=org.postgresql.Driver
server.port = 8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# westly boof
jwt.secret=tVrYjaMgI7KzVPxbl8FSN8DRMFvOKHsHsHgH9SRxvMCinBU57bnFNVs8DOPJKV+TRCmI10KQ/rSK/n8nauZ6xQ
jwt.expiration=86400000
api.prefix=/api
frontend.url=http://localhost:3000