spring.application.name=UNote

spring.datasource.url=jdbc:postgresql://localhost:5432/unote
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudflare.r2.access-key=${access_key}
cloudflare.r2.secret-key=${secret_key}
cloudflare.r2.account-id=${account_id}
cloudflare.r2.bucket=${bucket}
cloudflare.r2.public-url=https://pub-0ff40a08513b4654b96f3513f5719471.r2.dev

spring.servlet.multipart.max-file-size=${max_file_size}
spring.servlet.multipart.max-request-size=${max_file_request}
# westly boof
jwt.secret=dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciB1bm90ZSBhcHBsaWNhdGlvbiB0aGF0IGlzIDUxMiBiaXRzIGxvbmch
jwt.expiration=86400000
api.prefix=/api
