spring.application.name=UNote

spring.datasource.url=jdbc:postgresql://localhost:5432/unote
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudflare.r2.access-key=${access_key}
cloudflare.r2.secret-key=${secret_key}
cloudflare.r2.account-id=${account_id}
cloudflare.r2.bucket=${bucket}

spring.servlet.multipart.max-file-size=${max_file_size}
spring.servlet.multipart.max-request-size=${max_file_request}